# This is a basic workflow to help you get started with Actions

on: push
name: Build Gatsby Site
jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.x

    - name: Install dependencies
      run: yarn install --prod --pure-lockfile

    - name: Build
      run: yarn run build

